include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    require_trailing_commas: true
    prefer_single_quotes: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
