// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eaex0oFoRRJx5SBRvnq1RXIquqyWX4g',
    appId: '1:375219078541:web:81aec9e6ab72ba874729c4',
    messagingSenderId: '375219078541',
    projectId: 'planflow-27fd8',
    authDomain: 'planflow-27fd8.firebaseapp.com',
    storageBucket: 'planflow-27fd8.firebasestorage.app',
    measurementId: 'G-19TKZ6MS8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoy__DA0zyMHEDLhBcqBRhNFX8MSGJPCY',
    appId: '1:375219078541:android:ee3bace8a839c8b84729c4',
    messagingSenderId: '375219078541',
    projectId: 'planflow-27fd8',
    storageBucket: 'planflow-27fd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSo9j4CUdLPAbyGZRDBtNDA5MnrbH6k5E',
    appId: '1:375219078541:ios:61e74d58dd9d6d884729c4',
    messagingSenderId: '375219078541',
    projectId: 'planflow-27fd8',
    storageBucket: 'planflow-27fd8.firebasestorage.app',
    iosBundleId: 'com.planflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSo9j4CUdLPAbyGZRDBtNDA5MnrbH6k5E',
    appId: '1:375219078541:ios:61e74d58dd9d6d884729c4',
    messagingSenderId: '375219078541',
    projectId: 'planflow-27fd8',
    storageBucket: 'planflow-27fd8.firebasestorage.app',
    iosBundleId: 'com.planflow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1eaex0oFoRRJx5SBRvnq1RXIquqyWX4g',
    appId: '1:375219078541:web:01f5f4221a4643b64729c4',
    messagingSenderId: '375219078541',
    projectId: 'planflow-27fd8',
    authDomain: 'planflow-27fd8.firebaseapp.com',
    storageBucket: 'planflow-27fd8.firebasestorage.app',
    measurementId: 'G-507HFCW7HJ',
  );

}