#!/usr/bin/env bash
# Contract/regression tests for scripts/ios/e2e_summarize.sh.
#
# These are NOT unit tests with mocks: each case writes a real fixture log
# file to a temp directory and runs the actual e2e_summarize.sh as a
# subprocess against it, then greps the real summary file it produces. Per
# this repo's existing safety-gate convention ("a safety gate needs at least
# one test that passes real input through it, not just a test that mocks the
# thing the gate reads"), this file is that real-input test for the
# summarizer's fail-open/fail-closed classification of an incomplete build.
#
# Background bug this file guards against: build_succeeded_then_silent()
# (now build_completion_status()) used to return a single boolean, so "no
# 'Xcode build done' line at all" (the build never finished) and "build
# finished, output continued normally" were both reported as "정상" by the
# caller. A run that never reaches the build-done line has made LESS
# progress than one that hangs right after it, so collapsing the two into
# "normal" was a fail-open misclassification. See the "BUILD_NEVER_COMPLETED"
# category added in scripts/ios/e2e_summarize.sh for the fix.
#
# Usage: bash scripts/ios/tests/e2e_script_contract.sh
# Exit code: 0 if every case passes, 1 if any case fails (each failure is
# printed with the fixture name, the expected substring, and the actual
# summary content so a failure is diagnosable without re-running by hand).

set -uo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
summarize_script="$script_dir/../e2e_summarize.sh"

if [ ! -f "$summarize_script" ]; then
  echo "e2e_script_contract.sh: cannot find e2e_summarize.sh at $summarize_script" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf -- "$tmp_dir"
}
trap cleanup EXIT

pass_count=0
fail_count=0

# assert_contains <case_name> <log_content> <expected_substring> [flow_files_arg]
#
# Writes log_content to a fixture log file, runs e2e_summarize.sh against it
# with category "mainstream", and asserts the generated summary contains
# expected_substring. Prints PASS/FAIL for each case; never aborts the whole
# suite on one failure, so a single run reports every mismatch at once.
assert_contains() {
  local case_name="$1"
  local log_content="$2"
  local expected_substring="$3"
  local flow_files_arg="${4:-}"

  local log_file="$tmp_dir/${case_name}.log"
  local summary_file="$tmp_dir/${case_name}.summary.md"

  printf '%s\n' "$log_content" > "$log_file"

  if ! bash "$summarize_script" "mainstream" "$log_file" "$summary_file" "$flow_files_arg" >/dev/null 2>"$tmp_dir/${case_name}.stderr"; then
    echo "FAIL: $case_name — e2e_summarize.sh exited non-zero"
    echo "  stderr: $(cat "$tmp_dir/${case_name}.stderr" 2>/dev/null || true)"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if [ ! -f "$summary_file" ]; then
    echo "FAIL: $case_name — summary file was not written: $summary_file"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if grep -qF -- "$expected_substring" "$summary_file"; then
    echo "PASS: $case_name (found: \"$expected_substring\")"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected substring not found: \"$expected_substring\""
    echo "  --- actual summary ($summary_file) ---"
    sed 's/^/  /' "$summary_file"
    echo "  --- end summary ---"
    fail_count=$((fail_count + 1))
  fi
}

# assert_not_contains <case_name_for_message> <summary_file> <forbidden_substring>
#
# Companion to assert_contains for asserting an old/wrong classification did
# NOT reappear in a summary already generated by a prior assert_contains call
# for the same case_name.
assert_not_contains() {
  local case_name="$1"
  local forbidden_substring="$2"
  local summary_file="$tmp_dir/${case_name}.summary.md"

  if [ ! -f "$summary_file" ]; then
    echo "FAIL: $case_name (negative check) — summary file missing: $summary_file"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if grep -qF -- "$forbidden_substring" "$summary_file"; then
    echo "FAIL: $case_name — forbidden substring found: \"$forbidden_substring\""
    fail_count=$((fail_count + 1))
  else
    echo "PASS: $case_name (confirmed absent: \"$forbidden_substring\")"
    pass_count=$((pass_count + 1))
  fi
}

echo "=== e2e_summarize.sh contract tests ==="
echo ""

# --- Fixture A: "Xcode build done" line is entirely absent -----------------
# The build never finished within the captured log. Must be classified as
# BUILD_NEVER_COMPLETED, and must NOT be reported as "정상" (normal) the way
# the pre-fix fail-open bug did.
fixture_a_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:12 Launching lldb...
[STEP] watchdog: still waiting for xcodebuild to finish (elapsed 600s)
'
assert_contains "fixture_a_never_completed" "$fixture_a_log" 'Category guess: `BUILD_NEVER_COMPLETED`'
assert_contains "fixture_a_never_completed" "$fixture_a_log" '빌드가 캡처된 로그 안에서 완료되지 못함'
assert_not_contains "fixture_a_never_completed" '- Post-build 출력: 정상'

# --- Fixture B: "Xcode build done" present, nothing meaningful after it ----
# Must keep the existing BUILD_SUCCEEDED_THEN_SILENT classification (this is
# the run-2 hang signature and must not regress).
fixture_b_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
'
assert_contains "fixture_b_succeeded_then_silent" "$fixture_b_log" 'Category guess: `BUILD_SUCCEEDED_THEN_SILENT`'
assert_contains "fixture_b_succeeded_then_silent" "$fixture_b_log" '이후 유의미한 로그 라인 없음'
assert_not_contains "fixture_b_succeeded_then_silent" 'BUILD_NEVER_COMPLETED'

# --- Fixture C: "Xcode build done" present, real output follows it --------
# The healthy/normal shape. Must be reported as normal, and must NOT be
# misclassified as either of the two failure shapes above.
fixture_c_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
00:45 [CHECKPOINT] flow01_before_login
01:10 +12 -0: All tests passed!
'
assert_contains "fixture_c_normal" "$fixture_c_log" '- Post-build 출력: 정상'
assert_contains "fixture_c_normal" "$fixture_c_log" 'No failure markers detected'
assert_not_contains "fixture_c_normal" 'BUILD_NEVER_COMPLETED'
assert_not_contains "fixture_c_normal" 'BUILD_SUCCEEDED_THEN_SILENT'

echo ""
echo "--- Existing scenario regression checks (must still work unchanged) ---"
echo ""

# --- Regression: APP_INSTALL classification via a flow-file failure line --
fixture_install_log='00:01 Booting simulator...
00:05 xcrun simctl install failed: Unable to install "PlanFlow.app"
00:06 00:06 +0 -1: /path/integration_test/flow01_login_test.dart: some test [E]
00:07   Unable to install PlanFlow.app on the simulator
00:40 Xcode build done.
00:45 more output here so this run is not silent
'
assert_contains "regression_app_install" "$fixture_install_log" 'Category guess: `APP_INSTALL`' "integration_test/flow01_login_test.dart"

# --- Regression: XCODE_BUILD classification via whole-log fallback --------
fixture_build_failed_log='00:01 Booting simulator...
00:30 ** BUILD FAILED **
00:31 xcodebuild: error: something failed to compile
'
assert_contains "regression_xcode_build_failed" "$fixture_build_failed_log" 'Category guess: `XCODE_BUILD`'

# --- Regression: WATCHDOG_TIMEOUT classification --------------------------
fixture_watchdog_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
[STEP] watchdog: command exceeded 780s timeout, sending SIGTERM
::error title=E2E_WATCHDOG_TIMEOUT::mainstream leg exceeded its time budget
'
assert_contains "regression_watchdog_timeout" "$fixture_watchdog_log" 'Category guess: `WATCHDOG_TIMEOUT`'
assert_contains "regression_watchdog_timeout" "$fixture_watchdog_log" 'Watchdog: 타임아웃으로 종료됨'

# --- Regression: last [CHECKPOINT] marker is recognized and reported ------
fixture_checkpoint_log='00:01 Booting simulator...
00:40 Xcode build done.
00:41 [CHECKPOINT] flow03_before_reminder_save
00:42 [CHECKPOINT] flow03_after_reminder_save
01:00 +5 -0: All tests passed!
'
assert_contains "regression_checkpoint_marker" "$fixture_checkpoint_log" '마지막 도달 체크포인트: `flow03_after_reminder_save`'

# --- Regression: absent checkpoint log gets the "known limitation" wording,
#     not a claim that the run made no progress ----------------------------
fixture_no_checkpoint_log='00:01 Booting simulator...
00:40 Xcode build done.
01:00 +5 -0: All tests passed!
'
assert_contains "regression_no_checkpoint" "$fixture_no_checkpoint_log" '채널 자체가 부재'
assert_contains "regression_no_checkpoint" "$fixture_no_checkpoint_log" '테스트가 해당 체크포인트에 미도달했다는 뜻과 구분할 수 없음'

echo ""
echo "=== e2e_watchdog.sh contract tests (verbose-overhead investigation) ==="
echo ""

watchdog_script="$script_dir/../e2e_watchdog.sh"

if [ ! -f "$watchdog_script" ]; then
  echo "e2e_script_contract.sh: cannot find e2e_watchdog.sh at $watchdog_script" >&2
  exit 1
fi

# These cases run the real script as a subprocess (no mocks) against real
# temp files and real child commands (bash -c '...', sleep), per this repo's
# "a safety gate needs at least one test that passes real input through it"
# convention. E2E_WATCHDOG_FORCE_BASH=1 pins every case to the bash-fallback
# path so the suite is deterministic across dev boxes that do/don't have GNU
# coreutils `timeout` installed; the GNU-timeout path shares the exact same
# redirection/heartbeat/dump code paths (see e2e_watchdog.sh) and is exercised
# manually against a real GNU `timeout` as part of this change's verification,
# documented in the delivery report rather than duplicated here.

# assert_rc <case_name> <expected_rc> <actual_rc>
assert_rc() {
  local case_name="$1"
  local expected_rc="$2"
  local actual_rc="$3"

  if [ "$expected_rc" = "$actual_rc" ]; then
    echo "PASS: $case_name (rc=$actual_rc)"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected rc=$expected_rc, got rc=$actual_rc"
    fail_count=$((fail_count + 1))
  fi
}

# assert_output_contains <case_name> <output> <expected_substring>
assert_output_contains() {
  local case_name="$1"
  local output="$2"
  local expected_substring="$3"

  if printf '%s' "$output" | grep -qF -- "$expected_substring"; then
    echo "PASS: $case_name (found: \"$expected_substring\")"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected substring not found: \"$expected_substring\""
    echo "  --- actual output ---"
    printf '%s\n' "$output" | sed 's/^/  /'
    echo "  --- end output ---"
    fail_count=$((fail_count + 1))
  fi
}

# assert_output_not_contains <case_name> <output> <forbidden_substring>
assert_output_not_contains() {
  local case_name="$1"
  local output="$2"
  local forbidden_substring="$3"

  if printf '%s' "$output" | grep -qF -- "$forbidden_substring"; then
    echo "FAIL: $case_name — forbidden substring found: \"$forbidden_substring\""
    echo "  --- actual output ---"
    printf '%s\n' "$output" | sed 's/^/  /'
    echo "  --- end output ---"
    fail_count=$((fail_count + 1))
  else
    echo "PASS: $case_name (confirmed absent: \"$forbidden_substring\")"
    pass_count=$((pass_count + 1))
  fi
}

watchdog_tmp_dir="$(mktemp -d)"
watchdog_cleanup() {
  rm -rf -- "$watchdog_tmp_dir"
}
trap 'watchdog_cleanup; cleanup' EXIT

# --- Regression: opt-in options unset must not change existing behavior ----
regression_success_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 bash "$watchdog_script" 5 bash -c 'exit 0' 2>&1)"
regression_success_rc=$?
assert_rc "watchdog_regression_success_no_opts" "0" "$regression_success_rc"
assert_output_not_contains "watchdog_regression_success_no_opts_no_dump" "$regression_success_output" '::group::watchdog tail'

regression_timeout_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 bash "$watchdog_script" 2 sleep 30 2>&1)"
regression_timeout_rc=$?
assert_rc "watchdog_regression_timeout_no_opts" "124" "$regression_timeout_rc"
assert_output_contains "watchdog_regression_timeout_no_opts_message" "$regression_timeout_output" 'E2E_WATCHDOG_TIMEOUT'

# --- P2: opt-in redirection keeps child output out of the console ----------
redirect_log="$watchdog_tmp_dir/p2_child.log"
redirect_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$redirect_log" \
  bash "$watchdog_script" 5 bash -c 'echo "should not appear on console"; exit 0' 2>&1)"
redirect_rc=$?
assert_rc "watchdog_p2_redirect_rc" "0" "$redirect_rc"
assert_output_not_contains "watchdog_p2_redirect_console_silent" "$redirect_output" 'should not appear on console'
if [ -f "$redirect_log" ] && grep -qF 'should not appear on console' "$redirect_log"; then
  echo "PASS: watchdog_p2_redirect_log_file_has_child_output"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_p2_redirect_log_file_has_child_output — expected line not found in $redirect_log"
  fail_count=$((fail_count + 1))
fi

# --- P3: heartbeat reports growth (delta>0) while the child is producing ---
heartbeat_growing_log="$watchdog_tmp_dir/p3_growing.log"
heartbeat_growing_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_growing_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 4 bash -c 'for i in 1 2 3; do echo "growing line $i"; sleep 1; done; exit 0' 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_shows_positive_delta" "$heartbeat_growing_output" 'delta=+1'

# --- P3: heartbeat reports delta=+0 while the child is silent (stuck) ------
heartbeat_stuck_log="$watchdog_tmp_dir/p3_stuck.log"
heartbeat_stuck_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_stuck_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 sleep 30 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_shows_zero_delta_when_stuck" "$heartbeat_stuck_output" 'delta=+0'

# --- P3: heartbeat is a no-op (with a warning) when no log file is set -----
heartbeat_no_log_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 bash -c 'exit 0' 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_disabled_without_log_file" "$heartbeat_no_log_output" 'heartbeat disabled'
assert_output_not_contains "watchdog_p3_no_heartbeat_lines_without_log_file" "$heartbeat_no_log_output" 'delta=+'

# --- P3: heartbeat's last= field is masked, never raw secret text ----------
heartbeat_secret_log="$watchdog_tmp_dir/p3_secret.log"
heartbeat_secret_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_secret_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 bash -c 'echo "API_KEY=totallysecretvalue123"; sleep 5' 2>&1)"
assert_output_not_contains "watchdog_p3_heartbeat_masks_secret" "$heartbeat_secret_output" 'totallysecretvalue123'
assert_output_contains "watchdog_p3_heartbeat_masked_placeholder_present" "$heartbeat_secret_output" 'API_KEY=<MASKED>'

# --- P4: on timeout with a redirected log, dump the tail + scan milestones -
milestone_log="$watchdog_tmp_dir/p4_milestone.log"
milestone_tail_out="$watchdog_tmp_dir/p4_milestone.tail.txt"
milestone_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$milestone_log" E2E_WATCHDOG_TAIL_FILE="$milestone_tail_out" \
  bash "$watchdog_script" 2 bash -c '
    echo "00:05 Installing PlanFlow.app..."
    echo "00:40 Xcode build done."
    echo "API_KEY=anothersecretvalue999 listening on port 1234"
    sleep 30
  ' 2>&1)"
milestone_rc=$?
assert_rc "watchdog_p4_timeout_dump_rc" "124" "$milestone_rc"
assert_output_contains "watchdog_p4_timeout_dump_tail_group" "$milestone_output" '::group::watchdog tail'
assert_output_contains "watchdog_p4_timeout_dump_milestone_installing" "$milestone_output" 'pattern: Installing'
assert_output_contains "watchdog_p4_timeout_dump_milestone_build_done" "$milestone_output" 'pattern: Xcode build done'
assert_output_contains "watchdog_p4_timeout_dump_milestone_listening" "$milestone_output" 'pattern: listening on'
assert_output_not_contains "watchdog_p4_timeout_dump_masks_secret" "$milestone_output" 'anothersecretvalue999'
if [ -f "$milestone_tail_out" ] && grep -qF 'Xcode build done' "$milestone_tail_out" && ! grep -qF 'anothersecretvalue999' "$milestone_tail_out"; then
  echo "PASS: watchdog_p4_tail_file_saved_and_masked"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_p4_tail_file_saved_and_masked — expected masked tail content in $milestone_tail_out"
  fail_count=$((fail_count + 1))
fi

# --- P4: no matching milestones must say so honestly, not fabricate a match
no_milestone_log="$watchdog_tmp_dir/p4_no_milestone.log"
no_milestone_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$no_milestone_log" \
  bash "$watchdog_script" 3 bash -c 'echo "hello world"; echo "nothing special here"; exit 5' 2>&1)"
no_milestone_rc=$?
assert_rc "watchdog_p4_failure_no_timeout_rc" "5" "$no_milestone_rc"
assert_output_contains "watchdog_p4_no_milestone_honest_message" "$no_milestone_output" '마일스톤 매치 없음'

# --- P4: fail-open — missing/empty redirected log never changes the exit
#     code contract, and dump is skipped rather than erroring -------------
empty_log="$watchdog_tmp_dir/p4_empty.log"
empty_log_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$empty_log" \
  bash "$watchdog_script" 2 sleep 30 2>&1)"
empty_log_rc=$?
assert_rc "watchdog_p4_empty_log_rc_unaffected" "124" "$empty_log_rc"
assert_output_contains "watchdog_p4_empty_log_skip_message" "$empty_log_output" 'skipping timeout/failure tail dump'
assert_output_not_contains "watchdog_p4_empty_log_no_dump_group" "$empty_log_output" '::group::watchdog tail'

# --- Process hygiene: no orphaned heartbeat/child processes survive any of
#     the above cases (each of them used a bounded timeout, so by the time
#     control returns here every backgrounded process must be gone) --------
leftover_sleep_pids="$(pgrep -f 'sleep 30' 2>/dev/null || true)"
if [ -z "$leftover_sleep_pids" ]; then
  echo "PASS: watchdog_no_orphan_processes"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_no_orphan_processes — leftover 'sleep 30' PIDs: $leftover_sleep_pids"
  fail_count=$((fail_count + 1))
fi

echo ""
echo "=== Results: $pass_count passed, $fail_count failed ==="

if [ "$fail_count" -gt 0 ]; then
  exit 1
fi
exit 0
