#!/usr/bin/env bash
# Contract/regression tests for scripts/ios/e2e_summarize.sh.
#
# These are NOT unit tests with mocks: each case writes a real fixture log
# file to a temp directory and runs the actual e2e_summarize.sh as a
# subprocess against it, then greps the real summary file it produces. Per
# this repo's existing safety-gate convention ("a safety gate needs at least
# one test that passes real input through it, not just a test that mocks the
# thing the gate reads"), this file is that real-input test for the
# summarizer's fail-open/fail-closed classification of an incomplete build.
#
# Background bug this file guards against: build_succeeded_then_silent()
# (now build_completion_status()) used to return a single boolean, so "no
# 'Xcode build done' line at all" (the build never finished) and "build
# finished, output continued normally" were both reported as "정상" by the
# caller. A run that never reaches the build-done line has made LESS
# progress than one that hangs right after it, so collapsing the two into
# "normal" was a fail-open misclassification. See the "BUILD_NEVER_COMPLETED"
# category added in scripts/ios/e2e_summarize.sh for the fix.
#
# Usage: bash scripts/ios/tests/e2e_script_contract.sh
# Exit code: 0 if every case passes, 1 if any case fails (each failure is
# printed with the fixture name, the expected substring, and the actual
# summary content so a failure is diagnosable without re-running by hand).

set -uo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
summarize_script="$script_dir/../e2e_summarize.sh"

if [ ! -f "$summarize_script" ]; then
  echo "e2e_script_contract.sh: cannot find e2e_summarize.sh at $summarize_script" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf -- "$tmp_dir"
}
trap cleanup EXIT

pass_count=0
fail_count=0
skip_count=0

# assert_contains <case_name> <log_content> <expected_substring> [flow_files_arg]
#
# Writes log_content to a fixture log file, runs e2e_summarize.sh against it
# with category "mainstream", and asserts the generated summary contains
# expected_substring. Prints PASS/FAIL for each case; never aborts the whole
# suite on one failure, so a single run reports every mismatch at once.
assert_contains() {
  local case_name="$1"
  local log_content="$2"
  local expected_substring="$3"
  local flow_files_arg="${4:-}"

  local log_file="$tmp_dir/${case_name}.log"
  local summary_file="$tmp_dir/${case_name}.summary.md"

  printf '%s\n' "$log_content" > "$log_file"

  if ! bash "$summarize_script" "mainstream" "$log_file" "$summary_file" "$flow_files_arg" >/dev/null 2>"$tmp_dir/${case_name}.stderr"; then
    echo "FAIL: $case_name — e2e_summarize.sh exited non-zero"
    echo "  stderr: $(cat "$tmp_dir/${case_name}.stderr" 2>/dev/null || true)"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if [ ! -f "$summary_file" ]; then
    echo "FAIL: $case_name — summary file was not written: $summary_file"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if grep -qF -- "$expected_substring" "$summary_file"; then
    echo "PASS: $case_name (found: \"$expected_substring\")"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected substring not found: \"$expected_substring\""
    echo "  --- actual summary ($summary_file) ---"
    sed 's/^/  /' "$summary_file"
    echo "  --- end summary ---"
    fail_count=$((fail_count + 1))
  fi
}

# assert_not_contains <case_name_for_message> <summary_file> <forbidden_substring>
#
# Companion to assert_contains for asserting an old/wrong classification did
# NOT reappear in a summary already generated by a prior assert_contains call
# for the same case_name.
assert_not_contains() {
  local case_name="$1"
  local forbidden_substring="$2"
  local summary_file="$tmp_dir/${case_name}.summary.md"

  if [ ! -f "$summary_file" ]; then
    echo "FAIL: $case_name (negative check) — summary file missing: $summary_file"
    fail_count=$((fail_count + 1))
    return 0
  fi

  if grep -qF -- "$forbidden_substring" "$summary_file"; then
    echo "FAIL: $case_name — forbidden substring found: \"$forbidden_substring\""
    fail_count=$((fail_count + 1))
  else
    echo "PASS: $case_name (confirmed absent: \"$forbidden_substring\")"
    pass_count=$((pass_count + 1))
  fi
}

echo "=== e2e_summarize.sh contract tests ==="
echo ""

# --- Fixture A: "Xcode build done" line is entirely absent -----------------
# The build never finished within the captured log. Must be classified as
# BUILD_NEVER_COMPLETED, and must NOT be reported as "정상" (normal) the way
# the pre-fix fail-open bug did.
fixture_a_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:12 Launching lldb...
[STEP] watchdog: still waiting for xcodebuild to finish (elapsed 600s)
'
assert_contains "fixture_a_never_completed" "$fixture_a_log" 'Category guess: `BUILD_NEVER_COMPLETED`'
assert_contains "fixture_a_never_completed" "$fixture_a_log" '빌드가 캡처된 로그 안에서 완료되지 못함'
assert_not_contains "fixture_a_never_completed" '- Post-build 출력: 정상'

# --- Fixture B: "Xcode build done" present, nothing meaningful after it ----
# Must keep the existing BUILD_SUCCEEDED_THEN_SILENT classification (this is
# the run-2 hang signature and must not regress).
fixture_b_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
'
assert_contains "fixture_b_succeeded_then_silent" "$fixture_b_log" 'Category guess: `BUILD_SUCCEEDED_THEN_SILENT`'
assert_contains "fixture_b_succeeded_then_silent" "$fixture_b_log" '이후 유의미한 로그 라인 없음'
assert_not_contains "fixture_b_succeeded_then_silent" 'BUILD_NEVER_COMPLETED'

# --- Fixture C: "Xcode build done" present, real output follows it --------
# The healthy/normal shape. Must be reported as normal, and must NOT be
# misclassified as either of the two failure shapes above.
fixture_c_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
00:45 [CHECKPOINT] flow01_before_login
01:10 +12 -0: All tests passed!
'
assert_contains "fixture_c_normal" "$fixture_c_log" '- Post-build 출력: 정상'
assert_contains "fixture_c_normal" "$fixture_c_log" 'No failure markers detected'
assert_not_contains "fixture_c_normal" 'BUILD_NEVER_COMPLETED'
assert_not_contains "fixture_c_normal" 'BUILD_SUCCEEDED_THEN_SILENT'

# --- Fixture D: native XCTest crash after `Testing failed:` ----------------
# xcodebuild may fail the XCTest host before the Flutter reporter emits an
# "Xcode build done" line. This terminal marker must not be mislabeled as a
# build that never completed.
fixture_d_log='00:01 Booting simulator...
00:40 Testing failed:
00:40 Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
00:40 Crash: Runner (1234) GADApplicationVerifyPublisherInitializedCorrectly
'
assert_contains "fixture_d_native_xctest_failure" "$fixture_d_log" 'XCTEST_NATIVE_FAILURE'
assert_contains "fixture_d_native_xctest_failure" "$fixture_d_log" 'native XCTest 실행 실패 또는 호스트 crash'
assert_not_contains "fixture_d_native_xctest_failure" 'BUILD_NEVER_COMPLETED'

echo ""
echo "--- Existing scenario regression checks (must still work unchanged) ---"
echo ""

# --- Regression: APP_INSTALL classification via a flow-file failure line --
fixture_install_log='00:01 Booting simulator...
00:05 xcrun simctl install failed: Unable to install "PlanFlow.app"
00:06 00:06 +0 -1: /path/integration_test/flow01_login_test.dart: some test [E]
00:07   Unable to install PlanFlow.app on the simulator
00:40 Xcode build done.
00:45 more output here so this run is not silent
'
assert_contains "regression_app_install" "$fixture_install_log" 'Category guess: `APP_INSTALL`' "integration_test/flow01_login_test.dart"

# --- Regression: XCODE_BUILD classification via whole-log fallback --------
fixture_build_failed_log='00:01 Booting simulator...
00:30 ** BUILD FAILED **
00:31 xcodebuild: error: something failed to compile
'
assert_contains "regression_xcode_build_failed" "$fixture_build_failed_log" 'Category guess: `XCODE_BUILD`'

# --- Regression: WATCHDOG_TIMEOUT classification --------------------------
fixture_watchdog_log='00:01 Booting simulator...
00:05 Installing PlanFlow.app...
00:40 Xcode build done.
[STEP] watchdog: command exceeded 780s timeout, sending SIGTERM
::error title=E2E_WATCHDOG_TIMEOUT::mainstream leg exceeded its time budget
'
assert_contains "regression_watchdog_timeout" "$fixture_watchdog_log" 'Category guess: `WATCHDOG_TIMEOUT`'
assert_contains "regression_watchdog_timeout" "$fixture_watchdog_log" 'Watchdog: 타임아웃으로 종료됨'

# --- Regression: last [CHECKPOINT] marker is recognized and reported ------
fixture_checkpoint_log='00:01 Booting simulator...
00:40 Xcode build done.
00:41 [CHECKPOINT] flow03_before_reminder_save
00:42 [CHECKPOINT] flow03_after_reminder_save
01:00 +5 -0: All tests passed!
'
assert_contains "regression_checkpoint_marker" "$fixture_checkpoint_log" '마지막 도달 체크포인트: `flow03_after_reminder_save`'

# --- Regression: absent checkpoint log gets the "known limitation" wording,
#     not a claim that the run made no progress ----------------------------
fixture_no_checkpoint_log='00:01 Booting simulator...
00:40 Xcode build done.
01:00 +5 -0: All tests passed!
'
assert_contains "regression_no_checkpoint" "$fixture_no_checkpoint_log" '채널 자체가 부재'
assert_contains "regression_no_checkpoint" "$fixture_no_checkpoint_log" '테스트가 해당 체크포인트에 미도달했다는 뜻과 구분할 수 없음'

echo ""
echo "=== e2e_watchdog.sh contract tests (verbose-overhead investigation) ==="
echo ""

watchdog_script="$script_dir/../e2e_watchdog.sh"

if [ ! -f "$watchdog_script" ]; then
  echo "e2e_script_contract.sh: cannot find e2e_watchdog.sh at $watchdog_script" >&2
  exit 1
fi

# These cases run the real script as a subprocess (no mocks) against real
# temp files and real child commands (bash -c '...', sleep), per this repo's
# "a safety gate needs at least one test that passes real input through it"
# convention. Most cases pin E2E_WATCHDOG_FORCE_BASH=1 to the bash-fallback
# path so the suite is deterministic across dev boxes that do/don't have GNU
# coreutils `timeout` installed. (Review round-2 fix, LOW4: one case —
# "low4_gnu_timeout_path" below, near the H1 e2e case — deliberately leaves
# E2E_WATCHDOG_FORCE_BASH unset instead, so the GNU-timeout-backed path
# [resolve_gnu_timeout()] is actually exercised by this automated suite on
# any machine that has GNU coreutils `timeout`/`gtimeout`, rather than only
# ever being checked by hand and written up in a delivery report. On a
# machine without GNU timeout it harmlessly falls back to the same bash path
# every other case already covers.)

# assert_rc <case_name> <expected_rc> <actual_rc>
assert_rc() {
  local case_name="$1"
  local expected_rc="$2"
  local actual_rc="$3"

  if [ "$expected_rc" = "$actual_rc" ]; then
    echo "PASS: $case_name (rc=$actual_rc)"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected rc=$expected_rc, got rc=$actual_rc"
    fail_count=$((fail_count + 1))
  fi
}

# assert_output_contains <case_name> <output> <expected_substring>
assert_output_contains() {
  local case_name="$1"
  local output="$2"
  local expected_substring="$3"

  if printf '%s' "$output" | grep -qF -- "$expected_substring"; then
    echo "PASS: $case_name (found: \"$expected_substring\")"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — expected substring not found: \"$expected_substring\""
    echo "  --- actual output ---"
    printf '%s\n' "$output" | sed 's/^/  /'
    echo "  --- end output ---"
    fail_count=$((fail_count + 1))
  fi
}

# assert_output_not_contains <case_name> <output> <forbidden_substring>
assert_output_not_contains() {
  local case_name="$1"
  local output="$2"
  local forbidden_substring="$3"

  if printf '%s' "$output" | grep -qF -- "$forbidden_substring"; then
    echo "FAIL: $case_name — forbidden substring found: \"$forbidden_substring\""
    echo "  --- actual output ---"
    printf '%s\n' "$output" | sed 's/^/  /'
    echo "  --- end output ---"
    fail_count=$((fail_count + 1))
  else
    echo "PASS: $case_name (confirmed absent: \"$forbidden_substring\")"
    pass_count=$((pass_count + 1))
  fi
}

watchdog_tmp_dir="$(mktemp -d)"
watchdog_cleanup() {
  rm -rf -- "$watchdog_tmp_dir"
}
trap 'watchdog_cleanup; cleanup' EXIT

# --- Orphan-detection helpers (review round-2 fix, MEDIUM) ------------------
#
# Both orphan-leak checks further below (`watchdog_l4_no_orphan_heartbeat_sleep`
# and `watchdog_no_orphan_processes`) used to be `pgrep -f '<pattern>'
# 2>/dev/null || true`. On any machine without `pgrep` installed (this dev
# box is one: `command -v pgrep` returns nothing), that invocation fails,
# `2>/dev/null` swallows the "command not found" stderr, and `|| true` turns
# the whole thing into an unconditional empty string — i.e. the check always
# reports "no leftovers", not because it looked and found none, but because
# it never looked at all. `pgrep -f 'sleep 30' 2>/dev/null || true` on a
# `pgrep`-less machine is `<empty>` regardless of whether a `sleep 30` is
# actually running. These helpers fix that by (a) falling back to a portable
# `ps`-based scan when `pgrep` is unavailable, and (b) reporting which
# mechanism actually ran so callers can tell a genuine "scanned and found
# nothing" apart from "could not scan at all" (fail-closed: "none" must never
# be silently treated as PASS — see assert_no_new_orphan_pids below, which
# reports SKIP instead).
#
# NOTE: the scanning method is communicated via `_orphan_scan_method`'s own
# stdout, not a side-effect global variable set inside `_orphan_scan_pids`.
# Every call site below invokes these via `$(...)` command substitution,
# which bash always runs in a subshell — an assignment made inside that
# subshell (e.g. `ORPHAN_SCAN_METHOD="ps"`) never propagates back to the
# calling shell. An earlier draft of this fix used exactly that pattern and
# it silently always reported "none" even when `ps` scanning was actually
# available and working correctly (caught by manually inspecting this
# suite's own PASS/SKIP output before trusting it, the same self-check
# discipline item 3 below applies to the detector itself).

# _orphan_scan_method
#
# Prints "pgrep", "ps", or "none" depending on what is available on this
# machine to scan process command lines with. Pure stdout, no side effects,
# safe to call from inside a `$(...)` command substitution.
_orphan_scan_method() {
  if command -v pgrep >/dev/null 2>&1; then
    echo "pgrep"
  elif command -v ps >/dev/null 2>&1; then
    echo "ps"
  else
    echo "none"
  fi
}

# _orphan_scan_pids <pattern>
#
# Prints one PID per line for every process whose full command line matches
# <pattern> (a basic ERE, per grep -E). Uses whichever scanner
# `_orphan_scan_method` reports:
#   - pgrep: `pgrep -f -- <pattern>`.
#   - ps: `ps aux` + `ps -ef` combined. Neither flavor is trusted alone: on
#     this dev box `ps aux`'s COMMAND column is truncated to the bare binary
#     name with no arguments at all (so `sleep 30` shows up as plain
#     `sleep`, never matching a pattern that includes the argument), while
#     `ps -ef` here does carry the full command line; other platforms
#     (macOS/Linux CI runners) have been observed with the opposite
#     asymmetry. Both are scanned so whichever flavor happens to carry the
#     arguments still produces a match. Trailing whitespace is stripped from
#     each line first so a padded COMMAND column does not defeat a caller's
#     `$`-anchored pattern (observed on this box: a `ps -ef` COMMAND column
#     for a running `sleep 4` rendered as `sleep 4 ` with a trailing space).
#   - none: prints nothing — callers MUST check `_orphan_scan_method`
#     themselves and treat "none" as "could not check", not "checked, found
#     none" (see assert_no_new_orphan_pids below).
#
# Self-match pitfall (found while verifying this very fix): `ps ... | grep -E
# -- "$pattern"` as a single pipeline is WRONG when <pattern> can match the
# scan's own invocation — every stage of a shell pipeline is forked up front
# before any data flows, so `ps` captures a live snapshot that already
# includes the `grep -E -- "$pattern"` process sitting downstream in that
# same pipeline, and its own argv trivially contains <pattern>. This is not
# hypothetical: it reproduced deterministically for the "sleep 30" pattern
# used by the general hygiene check below (grep's own `grep -E sleep 30`
# argv matched itself every single run). The fix is to let `ps` finish and
# freeze its output into a variable FIRST (a command substitution blocks
# until the `ps` subshell exits and its pipe is closed), and only THEN grep
# that already-static text — by the time grep starts, `ps` and its snapshot
# are already gone, so grep is scanning old text, not the live process table
# it is itself a part of.
_orphan_scan_pids() {
  local pattern="$1"
  local method
  method="$(_orphan_scan_method)"

  case "$method" in
    pgrep)
      pgrep -f -- "$pattern" 2>/dev/null || true
      ;;
    ps)
      local snapshot
      snapshot="$( { ps aux 2>/dev/null; ps -ef 2>/dev/null; } )"
      printf '%s\n' "$snapshot" \
        | sed -E 's/[[:space:]]+$//' \
        | grep -E -- "$pattern" \
        | awk '{print $2}' \
        | sort -u
      ;;
    *)
      : # nothing to print — no scanner available
      ;;
  esac
}

# _orphan_scan_new_pids <baseline_pids> <current_pids>
#
# Prints (space-separated) every PID present in <current_pids> but absent
# from <baseline_pids>. Used to scope an orphan check to processes that
# appeared DURING this test run, instead of matching a generic pattern like
# "sleep 30" against the whole machine's process table — on this shared,
# multi-session dev box, an unrelated concurrent session running its own
# `sleep 30` for some other reason would otherwise be indistinguishable from
# a genuine leak (review finding: "타 세션이 같은 패턴 쓰면 거짓 FAIL도
# 가능"). A baseline captured immediately before the case under test spawns
# anything is effectively an identifying marker for "created by this test
# run", without needing to inject a literal marker string into
# e2e_watchdog.sh's production heartbeat/child-spawn code paths.
_orphan_scan_new_pids() {
  local baseline="$1"
  local current="$2"
  local pid
  local out=""

  while IFS= read -r pid; do
    [ -z "$pid" ] && continue
    if ! printf '%s\n' "$baseline" | grep -qxF -- "$pid"; then
      out="$out $pid"
    fi
  done <<EOF
$current
EOF

  printf '%s' "${out# }"
}

# assert_no_new_orphan_pids <case_name> <pattern> <baseline_pids>
#
# PASS when no NEW PID (relative to <baseline_pids>) still matches <pattern>.
# FAIL when at least one does. SKIP (never silently PASS) when neither pgrep
# nor ps was available to scan with at all.
assert_no_new_orphan_pids() {
  local case_name="$1"
  local pattern="$2"
  local baseline_pids="$3"

  local method
  method="$(_orphan_scan_method)"

  if [ "$method" = "none" ]; then
    echo "SKIP: $case_name — no process scanner available on this machine (neither pgrep nor ps was found); orphan-leak detection could not run for this case"
    skip_count=$((skip_count + 1))
    return 0
  fi

  local current_pids leaked_pids
  current_pids="$(_orphan_scan_pids "$pattern")"
  leaked_pids="$(_orphan_scan_new_pids "$baseline_pids" "$current_pids")"

  if [ -z "$leaked_pids" ]; then
    echo "PASS: $case_name (scanner: $method)"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL: $case_name — new PID(s) matching '$pattern' appeared since baseline and are still alive (scanner: $method): $leaked_pids"
    fail_count=$((fail_count + 1))
  fi
}

# Session-start baseline for the general process-hygiene check further below
# (`watchdog_no_orphan_processes`), captured before any of this suite's own
# `sleep 30` watchdog children have been spawned.
watchdog_hygiene_baseline_pids="$(_orphan_scan_pids 'sleep 30')"

# --- Orphan detector self-check (review round-2 fix, MEDIUM) ----------------
#
# Before trusting _orphan_scan_pids/_orphan_scan_new_pids to police the real
# scenarios below, prove they can actually detect a leak at all — the same
# thing the round-2 reviewer did by hand (deliberately create an orphan and
# confirm the detector catches it) before accepting the fix. Uses a duration
# ("sleep 2") not used as a literal child command by any other case in this
# file, so there is no risk of this self-check's own manufactured process
# being confused with (or masked by) one of the real scenarios' baselines.
self_check_method="$(_orphan_scan_method)"
self_check_pattern='sleep 2$'
self_check_baseline="$(_orphan_scan_pids "$self_check_pattern")"
sleep 2 &
self_check_pid=$!
self_check_current="$(_orphan_scan_pids "$self_check_pattern")"
self_check_leaked="$(_orphan_scan_new_pids "$self_check_baseline" "$self_check_current")"

if [ "$self_check_method" = "none" ]; then
  echo "SKIP: orphan_detector_self_check — no process scanner available on this machine; cannot verify the detector before relying on it below"
  skip_count=$((skip_count + 1))
elif [ -n "$self_check_leaked" ]; then
  echo "PASS: orphan_detector_self_check (scanner: $self_check_method found the deliberately-leaked PID(s): $self_check_leaked)"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: orphan_detector_self_check — detector reported no match for a deliberately-leaked 'sleep 2' process; the real orphan checks below cannot be trusted (scanner attempted: $self_check_method)"
  fail_count=$((fail_count + 1))
fi

# Let the manufactured process exit on its own — this repo's tooling blocks
# unowned process termination (`kill`/`pkill`/etc. are denied by a Bash
# PreToolUse hook regardless of ownership), so cleanup here is `wait`, not
# `kill`. This bounds the self-check's added wall time to ~2s.
wait "$self_check_pid" 2>/dev/null || true

# --- Regression: opt-in options unset must not change existing behavior ----
regression_success_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 bash "$watchdog_script" 5 bash -c 'exit 0' 2>&1)"
regression_success_rc=$?
assert_rc "watchdog_regression_success_no_opts" "0" "$regression_success_rc"
assert_output_not_contains "watchdog_regression_success_no_opts_no_dump" "$regression_success_output" '::group::watchdog tail'

regression_timeout_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 bash "$watchdog_script" 2 sleep 30 2>&1)"
regression_timeout_rc=$?
assert_rc "watchdog_regression_timeout_no_opts" "124" "$regression_timeout_rc"
assert_output_contains "watchdog_regression_timeout_no_opts_message" "$regression_timeout_output" 'E2E_WATCHDOG_TIMEOUT'

# --- P2: opt-in redirection keeps child output out of the console ----------
redirect_log="$watchdog_tmp_dir/p2_child.log"
redirect_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$redirect_log" \
  bash "$watchdog_script" 5 bash -c 'echo "should not appear on console"; exit 0' 2>&1)"
redirect_rc=$?
assert_rc "watchdog_p2_redirect_rc" "0" "$redirect_rc"
assert_output_not_contains "watchdog_p2_redirect_console_silent" "$redirect_output" 'should not appear on console'
if [ -f "$redirect_log" ] && grep -qF 'should not appear on console' "$redirect_log"; then
  echo "PASS: watchdog_p2_redirect_log_file_has_child_output"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_p2_redirect_log_file_has_child_output — expected line not found in $redirect_log"
  fail_count=$((fail_count + 1))
fi

# --- P3: heartbeat reports growth (delta>0) while the child is producing ---
heartbeat_growing_log="$watchdog_tmp_dir/p3_growing.log"
heartbeat_growing_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_growing_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 4 bash -c 'for i in 1 2 3; do echo "growing line $i"; sleep 1; done; exit 0' 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_shows_positive_delta" "$heartbeat_growing_output" 'delta=+1'

# --- P3: heartbeat reports delta=+0 while the child is silent (stuck) ------
heartbeat_stuck_log="$watchdog_tmp_dir/p3_stuck.log"
heartbeat_stuck_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_stuck_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 sleep 30 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_shows_zero_delta_when_stuck" "$heartbeat_stuck_output" 'delta=+0'

# --- P3: heartbeat is a no-op (with a warning) when no log file is set -----
heartbeat_no_log_output="$(env -u E2E_WATCHDOG_LOG_FILE -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 bash -c 'exit 0' 2>&1)"
assert_output_contains "watchdog_p3_heartbeat_disabled_without_log_file" "$heartbeat_no_log_output" 'heartbeat disabled'
assert_output_not_contains "watchdog_p3_no_heartbeat_lines_without_log_file" "$heartbeat_no_log_output" 'delta=+'

# --- P3: heartbeat's last= field is masked, never raw secret text ----------
heartbeat_secret_log="$watchdog_tmp_dir/p3_secret.log"
heartbeat_secret_output="$(env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_secret_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 3 bash -c 'echo "API_KEY=totallysecretvalue123"; sleep 5' 2>&1)"
assert_output_not_contains "watchdog_p3_heartbeat_masks_secret" "$heartbeat_secret_output" 'totallysecretvalue123'
assert_output_contains "watchdog_p3_heartbeat_masked_placeholder_present" "$heartbeat_secret_output" 'API_KEY=<MASKED>'

# --- P4: on timeout with a redirected log, dump the tail + scan milestones -
milestone_log="$watchdog_tmp_dir/p4_milestone.log"
milestone_tail_out="$watchdog_tmp_dir/p4_milestone.tail.txt"
milestone_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$milestone_log" E2E_WATCHDOG_TAIL_FILE="$milestone_tail_out" \
  bash "$watchdog_script" 2 bash -c '
    echo "00:05 Installing PlanFlow.app..."
    echo "00:40 Xcode build done."
    echo "API_KEY=anothersecretvalue999 listening on port 1234"
    sleep 30
  ' 2>&1)"
milestone_rc=$?
assert_rc "watchdog_p4_timeout_dump_rc" "124" "$milestone_rc"
assert_output_contains "watchdog_p4_timeout_dump_tail_group" "$milestone_output" '::group::watchdog tail'
assert_output_contains "watchdog_p4_timeout_dump_milestone_installing" "$milestone_output" 'pattern: Installing'
assert_output_contains "watchdog_p4_timeout_dump_milestone_build_done" "$milestone_output" 'pattern: Xcode build done'
assert_output_contains "watchdog_p4_timeout_dump_milestone_listening" "$milestone_output" 'pattern: listening on'
assert_output_not_contains "watchdog_p4_timeout_dump_masks_secret" "$milestone_output" 'anothersecretvalue999'
if [ -f "$milestone_tail_out" ] && grep -qF 'Xcode build done' "$milestone_tail_out" && ! grep -qF 'anothersecretvalue999' "$milestone_tail_out"; then
  echo "PASS: watchdog_p4_tail_file_saved_and_masked"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_p4_tail_file_saved_and_masked — expected masked tail content in $milestone_tail_out"
  fail_count=$((fail_count + 1))
fi

# --- P4: no matching milestones must say so honestly, not fabricate a match
no_milestone_log="$watchdog_tmp_dir/p4_no_milestone.log"
no_milestone_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$no_milestone_log" \
  bash "$watchdog_script" 3 bash -c 'echo "hello world"; echo "nothing special here"; exit 5' 2>&1)"
no_milestone_rc=$?
assert_rc "watchdog_p4_failure_no_timeout_rc" "5" "$no_milestone_rc"
assert_output_contains "watchdog_p4_no_milestone_honest_message" "$no_milestone_output" '마일스톤 매치 없음'

# --- P4: fail-open — missing/empty redirected log never changes the exit
#     code contract, and dump is skipped rather than erroring -------------
#
# NOTE (review fix, H1 side-effect): this used to exercise a *timeout*
# (`sleep 30` under a 2s bound) to reach an empty `log_file`, because before
# the H1 fix a timeout with a silent child truly left the redirected log at
# 0 bytes. After the H1 fix, watchdog_status() appends the watchdog's own
# timeout status line into that same log file, so a genuine timeout can no
# longer produce a 0-byte log — which is exactly the point of the fix (see
# the h1_e2e_real_timeout_detected_by_summarizer case above). The still-valid
# way to reach a genuinely empty log_file is a *non-timeout* failure whose
# child produces no stdout at all: watchdog_status() is only ever invoked on
# the timeout branches, so an ordinary nonzero exit with no output leaves
# log_file exactly as the initial truncate left it — empty — and this is
# still the fail-open path being asserted here.
empty_log="$watchdog_tmp_dir/p4_empty.log"
empty_log_output="$(env -u E2E_WATCHDOG_HEARTBEAT_INTERVAL -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$empty_log" \
  bash "$watchdog_script" 5 bash -c 'exit 7' 2>&1)"
empty_log_rc=$?
assert_rc "watchdog_p4_empty_log_rc_unaffected" "7" "$empty_log_rc"
assert_output_contains "watchdog_p4_empty_log_skip_message" "$empty_log_output" 'skipping timeout/failure tail dump'
assert_output_not_contains "watchdog_p4_empty_log_no_dump_group" "$empty_log_output" '::group::watchdog tail'
if [ -f "$empty_log" ] && [ ! -s "$empty_log" ]; then
  echo "PASS: watchdog_p4_empty_log_actually_empty"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: watchdog_p4_empty_log_actually_empty — expected $empty_log to exist and be 0 bytes"
  fail_count=$((fail_count + 1))
fi

# --- H1 regression (review fix): a REAL watchdog timeout, not a fixture that
#     writes watchdog lines directly into the log, must be detected by
#     e2e_summarize.sh's watchdog_timeout_line(). Before the H1 fix,
#     e2e_watchdog.sh's timeout status lines only ever reached its own
#     stderr/console (never E2E_WATCHDOG_LOG_FILE), so this exact scenario
#     silently reported "Watchdog: 타임아웃 신호 없음" in production even though
#     the run had, in fact, timed out — the "regression_watchdog_timeout"
#     fixture above cannot catch this because it writes the watchdog's status
#     lines into the log file by hand, which is an input production can never
#     actually produce on its own (mocked-contract-hides-bug). This case
#     instead runs the real watchdog end to end against a real hung child
#     (no tee anywhere in the pipeline, matching current production wiring),
#     feeds the log file it actually produced into the real summarizer, and
#     asserts the summarizer's own generated output reflects the timeout.
h1_e2e_log="$watchdog_tmp_dir/h1_e2e_real_timeout.log"
env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$h1_e2e_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 2 sleep 30 >/dev/null 2>&1
h1_e2e_watchdog_rc=$?
assert_rc "h1_e2e_real_watchdog_timeout_rc" "124" "$h1_e2e_watchdog_rc"

h1_e2e_summary="$tmp_dir/h1_e2e_real_timeout.summary.md"
if [ -f "$h1_e2e_log" ]; then
  bash "$summarize_script" "mainstream" "$h1_e2e_log" "$h1_e2e_summary" "" >/dev/null 2>&1
fi

if [ -f "$h1_e2e_summary" ] \
  && grep -qF 'Watchdog: 타임아웃으로 종료됨' "$h1_e2e_summary" \
  && ! grep -qF '타임아웃 신호 없음' "$h1_e2e_summary"; then
  echo "PASS: h1_e2e_real_timeout_detected_by_summarizer"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: h1_e2e_real_timeout_detected_by_summarizer — expected 'Watchdog: 타임아웃으로 종료됨' (and NOT '타임아웃 신호 없음') in $h1_e2e_summary"
  echo "  --- real watchdog log produced by e2e_watchdog.sh ($h1_e2e_log) ---"
  sed 's/^/  /' "$h1_e2e_log" 2>/dev/null || echo "  (missing)"
  echo "  --- end log ---"
  if [ -f "$h1_e2e_summary" ]; then
    echo "  --- generated summary ($h1_e2e_summary) ---"
    sed 's/^/  /' "$h1_e2e_summary"
    echo "  --- end summary ---"
  else
    echo "  (summary file was not written: $h1_e2e_summary)"
  fi
  fail_count=$((fail_count + 1))
fi

# --- LOW4 (review round-2 fix): h1_e2e above pins E2E_WATCHDOG_FORCE_BASH=1,
#     so only the bash-fallback timeout path (run_with_bash_fallback) was
#     ever exercised by this suite — the GNU-`timeout`-backed path
#     (resolve_gnu_timeout(), used automatically whenever this machine has
#     a GNU coreutils `timeout`/`gtimeout`, which several dev boxes and some
#     CI runners do) had no equivalent case, even though it shares the same
#     watchdog_status()/dump_tail_and_milestones() code paths this suite is
#     meant to validate. This mirrors h1_e2e_log's real-watchdog,
#     real-summarizer flow with E2E_WATCHDOG_FORCE_BASH left UNSET instead
#     of forced. On a machine without GNU timeout, resolve_gnu_timeout()
#     fails closed and this falls back to the exact same bash path h1_e2e
#     already covers, so the case is harmless (if redundant) there too —
#     it is asserted either way, never skipped, so this suite always proves
#     at least one of the two timeout paths this machine can actually reach.
low4_gnu_log="$watchdog_tmp_dir/low4_gnu_timeout_path.log"
env -u E2E_WATCHDOG_FORCE_BASH -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_LOG_FILE="$low4_gnu_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=1 \
  bash "$watchdog_script" 2 sleep 30 >/dev/null 2>&1
low4_gnu_watchdog_rc=$?
assert_rc "low4_gnu_timeout_path_rc" "124" "$low4_gnu_watchdog_rc"

low4_gnu_summary="$tmp_dir/low4_gnu_timeout_path.summary.md"
if [ -f "$low4_gnu_log" ]; then
  bash "$summarize_script" "mainstream" "$low4_gnu_log" "$low4_gnu_summary" "" >/dev/null 2>&1
fi

if [ -f "$low4_gnu_summary" ] \
  && grep -qF 'Watchdog: 타임아웃으로 종료됨' "$low4_gnu_summary" \
  && ! grep -qF '타임아웃 신호 없음' "$low4_gnu_summary"; then
  echo "PASS: low4_gnu_timeout_path_detected_by_summarizer"
  pass_count=$((pass_count + 1))
else
  echo "FAIL: low4_gnu_timeout_path_detected_by_summarizer — expected 'Watchdog: 타임아웃으로 종료됨' (and NOT '타임아웃 신호 없음') in $low4_gnu_summary"
  echo "  --- watchdog log ($low4_gnu_log) ---"
  sed 's/^/  /' "$low4_gnu_log" 2>/dev/null || echo "  (missing)"
  echo "  --- end log ---"
  if [ -f "$low4_gnu_summary" ]; then
    echo "  --- generated summary ($low4_gnu_summary) ---"
    sed 's/^/  /' "$low4_gnu_summary"
    echo "  --- end summary ---"
  else
    echo "  (summary file was not written: $low4_gnu_summary)"
  fi
  fail_count=$((fail_count + 1))
fi

# --- L4 regression (review fix): heartbeat's own `sleep <interval>` child
#     must not survive as an orphan after the watchdog exits. Uses a
#     heartbeat interval (5s) longer than the watchdog bound (2s) so the
#     heartbeat's `sleep 5` is still in-flight in the exact moment the
#     watchdog tears itself down — that overlap is the failure window the
#     shared-process-group fix targets. Checked immediately after the
#     watchdog process returns, with no grace sleep of our own: before the
#     fix, a lingering `sleep 5` process would still be alive right here (a
#     plain `kill $heartbeat_pid` only ever reaped the heartbeat subshell,
#     not the `sleep` grandchild it was blocked in).
#
#     (Review round-2 fix, MEDIUM: baseline is captured immediately before
#     spawning, and the leak check below only counts PIDs that are NEW since
#     that baseline — see _orphan_scan_new_pids above — instead of matching
#     'sleep 5$' against the whole machine's process table.)
heartbeat_orphan_log="$watchdog_tmp_dir/l4_heartbeat_orphan.log"
l4_heartbeat_sleep_pattern='sleep 5$'
l4_heartbeat_sleep_baseline="$(_orphan_scan_pids "$l4_heartbeat_sleep_pattern")"
env -u E2E_WATCHDOG_TAIL_FILE \
  E2E_WATCHDOG_FORCE_BASH=1 E2E_WATCHDOG_LOG_FILE="$heartbeat_orphan_log" E2E_WATCHDOG_HEARTBEAT_INTERVAL=5 \
  bash "$watchdog_script" 2 sleep 30 >/dev/null 2>&1
heartbeat_orphan_rc=$?
assert_rc "watchdog_l4_heartbeat_orphan_watchdog_rc" "124" "$heartbeat_orphan_rc"
assert_no_new_orphan_pids "watchdog_l4_no_orphan_heartbeat_sleep" "$l4_heartbeat_sleep_pattern" "$l4_heartbeat_sleep_baseline"

# --- Process hygiene: no orphaned heartbeat/child processes survive any of
#     the above cases (each of them used a bounded timeout, so by the time
#     control returns here every backgrounded process must be gone) --------
#
#     (Review round-2 fix, MEDIUM: uses the session-start baseline captured
#     before the very first case in this file spawned a 'sleep 30', for the
#     same reason as the L4 case above — see _orphan_scan_new_pids.)
assert_no_new_orphan_pids "watchdog_no_orphan_processes" "sleep 30" "$watchdog_hygiene_baseline_pids"

echo ""
echo "=== Results: $pass_count passed, $fail_count failed, $skip_count skipped ==="

if [ "$fail_count" -gt 0 ]; then
  exit 1
fi
exit 0
