create table if not exists jw_mr.professor_feedback (
  id bigint generated by default as identity primary key,
  professor_id bigint not null references jw_mr.professors(id) on delete cascade,
  feedback_date date not null default current_date,
  feedback_text text not null,
  feedback_type text not null default 'visit_feedback',
  related_detail_history_id bigint null references jw_mr.detail_history(id) on delete set null,
  apply_from date not null default current_date,
  apply_until date null,
  is_active boolean not null default true,
  priority integer not null default 100,
  created_at timestamptz not null default now()
);

create index if not exists professor_feedback_professor_idx on jw_mr.professor_feedback(professor_id, is_active, feedback_date desc);

insert into jw_mr.rules(rule_key, category, rule_text, priority, is_active, source)
values (
  'cumulative_professor_feedback_application',
  'professor_feedback',
  '사용자가 특정 교수의 방문 일정이나 디테일에 대해 피드백을 주면 해당 교수의 누적 피드백으로 저장한다. 이후 그 교수가 다시 일정 후보가 될 때 활성 피드백을 모두 조회해 제품 선택, 디테일 포인트, 표현, 피해야 할 내용, 선호 주제, 다음 방문 방향에 누적 반영한다. 최신 피드백과 명시적 사용자 정정이 우선하며, 기존 피드백과 충돌하면 최신 지시를 우선한다.',
  1000,
  true,
  'user'
)
on conflict (rule_key) do update set rule_text=excluded.rule_text, priority=excluded.priority, is_active=true, updated_at=now();;
